# Generated by Django 3.1.2 on 2020-10-15 15:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(max_length=250)),
                ('admins', models.ManyToManyField(blank=True, related_name='admins_room', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(blank=True, related_name='members_room', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
