# Generated by Django 3.1.2 on 2020-10-16 19:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0004_room_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='join_requests',
            field=models.ManyToManyField(blank=True, related_name='join_requests_room', to=settings.AUTH_USER_MODEL),
        ),
    ]
